# Generated by Django 5.2.7 on 2025-11-04 15:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('bridge_type', models.CharField(choices=[('BEAM_COMPOSITE', 'Beam Composite Bridge'), ('SUSPENSION', 'Suspension Bridge'), ('ARCH', 'Arch Bridge'), ('TRUSS', 'Truss Bridge')], max_length=50)),
                ('length', models.DecimalField(decimal_places=3, help_text='Length in meters', max_digits=6)),
                ('width', models.DecimalField(decimal_places=2, help_text='Width in meters', max_digits=5)),
                ('lanes', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('material', models.CharField(choices=[('STEEL_CONCRETE', 'Steel and Concrete'), ('CONCRETE', 'Concrete'), ('STEEL', 'Steel')], max_length=50)),
                ('year_built', models.PositiveIntegerField()),
                ('route', models.TextField(help_text='Route description')),
                ('gps_coordinates', models.TextField(help_text='GPS coordinates (comma-separated)')),
                ('deck_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('girders_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('piers_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('abutment_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('condition_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bridge',
                'verbose_name_plural': 'Bridges',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('MINOR_REPAIR', 'Minor Repairs'), ('ROUTINE', 'Routine Maintenance'), ('MONITORING', 'Normal Monitoring'), ('MAJOR_REPAIR', 'Major Repairs'), ('INSPECTION', 'Inspection')], max_length=50)),
                ('description', models.TextField()),
                ('scheduled_date', models.DateField()),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bridge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='bridges.bridge')),
            ],
            options={
                'verbose_name': 'Maintenance Record',
                'verbose_name_plural': 'Maintenance Records',
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='TrafficData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heavy_vehicles', models.PositiveIntegerField(default=0, help_text='Daily count')),
                ('small_vehicles', models.PositiveIntegerField(default=0, help_text='Daily count')),
                ('recorded_date', models.DateField(auto_now=True)),
                ('bridge', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='traffic', to='bridges.bridge')),
            ],
            options={
                'verbose_name': 'Traffic Data',
                'verbose_name_plural': 'Traffic Data',
            },
        ),
    ]
